### ISSUE TITLE
Px-app-header should expose branding bar config

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-app-helpers#6]
The application header should probably be customizable in px-app-header by exposing the property from px-branding-bar

**Comment by stephanepilla** [comment]
Actually, you can use your own instance of px-branding-bar in the light dom of px-app-header (using the "branding-bar" slot name).

You'll be able to customize your px-branding-bar.

**Comment by randyaskin** [comment]
Good to know, thanks. In that case I'll just make sure the slot info gets added to the documentation for this component.
