### ISSUE TITLE
Demo not loading for px-app-header

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-app-helpers#7]
The demo for px-app-header is not loading and throwing `babelHelpers is not defined` errors.

It looks like Polymer is being loaded in the demo iFrame and referencing babelHelpers before it is loaded.

![screen shot 2017-09-28 at 12 54 02 pm](https://user-images.githubusercontent.com/9092541/30992390-855ad59a-a45e-11e7-859d-aa23306fc47c.png)

**Comment by mdwragg** [comment]
Fixed in 6b64c9d63d9448d3b3285124f2e0081653681757 et al
