### ISSUE TITLE
Does px-app-route support dynamic urls pattern matching?

### ISSUE THREAD

**Issue by naveenjaiswal** [PredixDev/px-app-helpers#8]
I have upgraded my predix web starter app which changes its component  to px-app-route from polymer's app route. The use case is I have a dynamic url of the form https://localhost:5000/#/parkconditions/1013733/1213 where last two parameters are dynamic. As i am not able to find pattern matching in px-app-route which was there in app-route and connect it to px-view accordingly.

Expected: the polymer app route supports pattern matching.
Actual: px app route is not supporting pattern matching

**Comment by davidrleonard** [comment]
By default, px-app-route uses the app-location element to sync the page state with the window's location, and app-location has a urlSpaceRegex that should allow you to only deal with a dynamic portion of the URL: https://www.webcomponents.org/element/PolymerElements/app-route/elements/app-location#property-urlSpaceRegex
